// Design tokens & shared style constants for User Personaa Power-Up popups.
// Aligned with Atlassian Design System dark theme (#1D2125 background).

export const theme = {
  colors: {
    bg: "#1D2125",
    surface: "#22272B",
    surfaceHover: "#2C333A",
    border: "#333C43",
    borderSubtle: "rgba(255, 255, 255, 0.08)",
    primary: "#579DFF",
    primaryHover: "#85B8FF",
    primaryGlow: "rgba(87, 157, 255, 0.25)",
    personaAccent: "#8546FF",
    success: "#4BCE97",
    successBg: "rgba(75, 206, 151, 0.15)",
    error: "#F87168",
    errorBg: "rgba(248, 113, 104, 0.15)",
    text: "#F7F8F9",
    textSubtle: "#9FADBC",
    textMuted: "#738496",
  },
  shadows: {
    popup: "0 8px 24px rgba(0, 0, 0, 0.4)",
    button: "0 2px 8px rgba(87, 157, 255, 0.25)",
  },
  radii: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    pill: "9999px",
  },
};

export const popupStyles = {
  wrapper: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Outfit', sans-serif",
    padding: "18px 16px",
    background: theme.colors.bg,
    color: theme.colors.text,
    boxSizing: "border-box",
    minHeight: "100%",
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  title: {
    fontSize: "15px",
    fontWeight: "600",
    color: theme.colors.text,
    margin: 0,
    letterSpacing: "-0.2px",
  },
  body: {
    fontSize: "13px",
    color: theme.colors.textSubtle,
    lineHeight: 1.5,
    margin: "0 0 16px 0",
  },
  btnPrimary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    width: "100%",
    padding: "9px 16px",
    borderRadius: theme.radii.md,
    border: "none",
    background: `linear-gradient(135deg, ${theme.colors.primary} 0%, #388BFF 100%)`,
    color: "#091E42",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.15s ease",
    boxShadow: theme.shadows.button,
  },
  btnPrimaryBusy: {
    opacity: 0.75,
    cursor: "wait",
  },
  btnSecondary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    width: "100%",
    padding: "8px 14px",
    borderRadius: theme.radii.md,
    border: `1px solid ${theme.colors.border}`,
    background: theme.colors.surface,
    color: theme.colors.text,
    fontSize: "12.5px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "background 0.15s ease",
  },
  btnSubtle: {
    background: "transparent",
    border: "none",
    color: theme.colors.primaryHover,
    fontSize: "12px",
    cursor: "pointer",
    padding: "6px 0",
    width: "100%",
    textAlign: "center",
    textDecoration: "underline",
    display: "block",
  },
  btnDanger: {
    background: "transparent",
    border: `1px solid rgba(248, 113, 104, 0.4)`,
    color: theme.colors.error,
    fontSize: "12px",
    fontWeight: "500",
    borderRadius: theme.radii.md,
    padding: "6px 12px",
    cursor: "pointer",
    width: "100%",
    marginTop: "8px",
    transition: "background 0.15s ease",
  },
};
